### ISSUE TITLE
Email design glitch

### ISSUE THREAD

**Issue by michaelbaudino** [timecop-app/discuss#3]
Hi there,

Just a quick glitch report: I'm pretty sure blue text on blue background (in the confirmation email) wasn't what you intended :wink: 

![2020-04-30_10-36](https://user-images.githubusercontent.com/1447321/80690056-8d7e9280-8ace-11ea-9ef2-a9eae7488b33.png)

**Comment by guillaumebriday** [comment]
Thanks for the catch! 

Google adds its own style, we need to override it.

I fixed it, will be available in the upcoming release
